[package]
name = "xdp-backend"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zbus = "1.9"
zvariant = "2.7"
zvariant_derive = "2.7"
serde = "1.0"
